export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_FAILURE = "USERS_FAILURE";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";